### ISSUE TITLE
KeyError: 'SuperGiftPoints'

### ISSUE THREAD

**Issue by erygvy** [zsennenga/hades_save_editor#1]
As i stated, the program crashes with "KeyError: 'SuperGiftPoints'" as last prompt in command console
when i try to load the Profile1.sav file
here is my whole savegame folder
[Hades.zip](https://github.com/zsennenga/hades_save_editor/files/4060784/Hades.zip)

**Comment by zsennenga** [comment]
@erygvy Hey! I think this is fixed now, sorry, I didn't see this issue before. Please try out the new release and let me know!
