### ISSUE TITLE
Loading sav issue

### ISSUE THREAD

**Issue by throwpigeyaway** [zsennenga/hades_save_editor#11]
I get an error when I load a sav.

Error RuntimeError: input(): lost sys.stdin

**Comment by NeoNamE-GH** [comment]
Hi, me too having same error on save load:
Error RuntimeError: input(): lost sys.stdin
It is a run in progress, having some items and weapons already unlocked.
But it is working properly on new created save.
So the issue with this error is only with saves that have already some progress in the game. 
Thanks in advance.

**Comment by throwpigeyaway** [comment]
can confirm it works on new sav.

**Comment by zsennenga** [comment]
If you're having this issue, attach a save so I can investigate.

**Comment by NeoNamE-GH** [comment]
Hi, have the save attached.
[Profile1.zip](https://github.com/zsennenga/hades_save_editor/files/5258341/Profile1.zip)

**Comment by mphuie** [comment]
I could also not get the GUI part to work, but this worked in the REPL (or just write to a `.py` file)

`from models.save_file import HadesSaveFile
save_file = HadesSaveFile.from_file('<replace with your Profile#.sav>')
save_file.lua_state.darkness = float(40000)
save_file.lua_state.titan_blood = float(250)
save_file.lua_state.titan_blood = float(5000)
save_file.to_file('output file name')
`

**Comment by erkantaylan** [comment]
I am having same issue too, unedited version still works but edited version gives the same error.

[Hades_unedited.zip](https://github.com/zsennenga/hades_save_editor/files/5281856/Hades_unedited.zip)
[Hades_edited.zip](https://github.com/zsennenga/hades_save_editor/files/5281857/Hades_edited.zip)

**Comment by gkkirilov** [comment]
@mphuie Thanks!
For anyone wondering you need to write "continue" at some point of the execution

**Comment by zsennenga** [comment]
Should be resolved with the new version. Issue ended up being in the library I wrote to decode luabin content, not the save editor itself.

**Comment by zsennenga** [comment]
Closing pending more comments telling me this isn't resolved.
