### ISSUE TITLE
Post 1.0 small update seems to have broken the editor

### ISSUE THREAD

**Issue by LlamaLlamaLlamaLlama** [zsennenga/hades_save_editor#12]
Just gives this error in the attached image when trying to load a save.
![image](https://user-images.githubusercontent.com/71667206/93810310-4cb12280-fc03-11ea-8f4d-99f30cefe05b.png)

**Comment by ilevn** [comment]
This is a duplicate of #11

**Comment by LlamaLlamaLlamaLlama** [comment]
I thought that one was before the small update since it was from 2 days ago but okay.

**Comment by zsennenga** [comment]
This is indeed a duplicate, in general I'd recommend erring on posting in the same issue if you're not sure if it's a duplicate or not, particularly when it has the same error message.
