### ISSUE TITLE
Error Exception:Unsupported version16"

### ISSUE THREAD

**Issue by Rarehitman** [zsennenga/hades_save_editor#15]
I have tried to leave a room and load a new one and then exit, but I still get the same error.

**Comment by zsennenga** [comment]
Version 16 is the newest version, and the latest save editor supports that version. Are you using the latest version of the save editor?

**Comment by Rarehitman** [comment]
I deleted the ones I had and reinstalled, now I'm not sure how to run it.

**Comment by zsennenga** [comment]
It's just a windows exe file, so I'm not really sure how to advise you here. I've verified saves on the most recent hades version work with the most recent save editor, so I'm going to close this, sorry.

**Comment by Rarehitman** [comment]
when I click the files it pops open for a sec and then closes right away.
