### ISSUE TITLE
Program Crashes

### ISSUE THREAD

**Issue by JRHB314** [zsennenga/hades_save_editor#24]
Two separate issues. Number one is that the prgram crashes when I try to load Profile1.sav, which I assume is the correct file. It says Version 16 not supported?

The other is just a suggestion, which is your readme could have a bit more detail in terms of instructions. Something like:

First, hit Load. Go to such and such location to choose such and such file name to load in your current details.
Edit the values of each currency to your desired amount.
Save to such and location / filename. 

I mean, I'm assuming that's about how it's meant to work.

**Comment by zsennenga** [comment]
Version 16 is the version of the save introduced with the 1.0 update of hades. The version of the editor you're using is extremely old.
