### ISSUE TITLE
Support for version 16

### ISSUE THREAD

**Issue by Slim175** [zsennenga/hades_save_editor#8]
Hey dude, great work with this editor! Are you considering updating it to support the new update that recently came out?

**Comment by Mister-Corn** [comment]
@zsennenga @Slim175 

I'm trying to update this to support v16 save files. The change in the .sav file that seemed to break everything was an addition of  8 bytes after the version. Those 8 bytes record the timestamp of the save file in milliseconds. I got a successful read after adding that into the schema.

For a PR, I'd like to show that timestamp in the UI, and tweak things to make it save. It'll take me a couple of days (I got work 😰), but I can get that going.

**Comment by zsennenga** [comment]
I updated it for 1.0 support (your branch didn't seem to be 100% compatible, it appears they changed some of the padding settings), but if you'd like to add timestamp to the ui (or change the logic around it, I just sorta overwrite it with the current timestamp every time which is... bad) I'd be happy to get it merged in this time around :)
